language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tyagiankur07/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true tyagiankur07/docker-react npm run test