language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tyagiankur07/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tyagiankur07/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-us-east-1-238642485089"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
